# 구별 범죄 현황 데이터 생성

In [22]:
import pandas as pd

crime_anal_station = pd.read_csv(
    "./result_data/03_crime_in_seoul_raw_data.csv", encoding='utf-8'
    , index_col=0 # "구분" 컬럼을 Index로 설정
)
crime_anal_station.head()

,강간검거,강간발생,강도검거,강도발생,살인검거,살인발생,절도검거,절도발생,폭력검거,폭력발생,구별,lat,lng
구분,,,,,,,,,,,,,
강남,269.0,339.0,26.0,24.0,3.0,3.0,1129.0,2438.0,2096.0,2336.0,강남구,37.509435,127.066958
강동,152.0,160.0,13.0,14.0,5.0,4.0,902.0,1754.0,2201.0,2530.0,강동구,37.528511,127.126822
강북,159.0,217.0,4.0,5.0,6.0,7.0,672.0,1222.0,2482.0,2778.0,강북구,37.643480,127.011184
강서,239.0,275.0,10.0,10.0,10.0,9.0,1070.0,1952.0,2768.0,3204.0,강서구,37.551362,126.850280
관악,264.0,322.0,10.0,12.0,7.0,6.0,937.0,2103.0,2707.0,3235.0,관악구,37.474395,126.951349

#### 🔰 구별 데이터로 정리

> 서울은 한 구에 경찰서가 두 곳인 구가 있으므로 구의 이름으로 다시 정렬한다.

- 서울시 구는 25개, 서울 내 경찰서는 31곳

In [23]:
crime_anal_station.info()

<class 'pandas.core.frame.DataFrame'>
Index: 31 entries, 강남 to 혜화
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   강간검거    31 non-null     float64
 1   강간발생    31 non-null     float64
 2   강도검거    31 non-null     float64
 3   강도발생    31 non-null     float64
 4   살인검거    31 non-null     float64
 5   살인발생    31 non-null     float64
 6   절도검거    31 non-null     float64
 7   절도발생    31 non-null     float64
 8   폭력검거    31 non-null     float64
 9   폭력발생    31 non-null     float64
 10  구별      31 non-null     object
 11  lat     31 non-null     float64
 12  lng     31 non-null     float64
dtypes: float64(12), object(1)
memory usage: 3.4+ KB

In [24]:
import numpy as np

crime_anal_gu = pd.pivot_table(crime_anal_station, index="구별", aggfunc=np.sum)
crime_anal_gu.head()

,lat,lng,강간검거,강간발생,강도검거,강도발생,살인검거,살인발생,절도검거,절도발생,폭력검거,폭력발생
구별,,,,,,,,,,,,
강남구,75.002925,254.144170,413.0,516.0,42.0,39.0,5.0,5.0,1918.0,3587.0,3527.0,4002.0
강동구,37.528511,127.126822,152.0,160.0,13.0,14.0,5.0,4.0,902.0,1754.0,2201.0,2530.0
강북구,37.643480,127.011184,159.0,217.0,4.0,5.0,6.0,7.0,672.0,1222.0,2482.0,2778.0
강서구,37.551362,126.850280,239.0,275.0,10.0,10.0,10.0,9.0,1070.0,1952.0,2768.0,3204.0
관악구,37.474395,126.951349,264.0,322.0,10.0,12.0,7.0,6.0,937.0,2103.0,2707.0,3235.0

In [25]:
crime_anal_gu.info()

<class 'pandas.core.frame.DataFrame'>
Index: 25 entries, 강남구 to 중랑구
Data columns (total 12 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   lat     25 non-null     float64
 1   lng     25 non-null     float64
 2   강간검거    25 non-null     float64
 3   강간발생    25 non-null     float64
 4   강도검거    25 non-null     float64
 5   강도발생    25 non-null     float64
 6   살인검거    25 non-null     float64
 7   살인발생    25 non-null     float64
 8   절도검거    25 non-null     float64
 9   절도발생    25 non-null     float64
 10  폭력검거    25 non-null     float64
 11  폭력발생    25 non-null     float64
dtypes: float64(12)
memory usage: 2.5+ KB

- 필요 없는 컬럼 제거

In [26]:
del crime_anal_gu["lat"]
del crime_anal_gu["lng"]

crime_anal_gu.head()

      강간검거   강간발생  강도검거  강도발생  살인검거  살인발생    절도검거    절도발생    폭력검거    폭력발생
구별
강남구  413.0  516.0  42.0  39.0   5.0   5.0  1918.0  3587.0  3527.0  4002.0
강동구  152.0  160.0  13.0  14.0   5.0   4.0   902.0  1754.0  2201.0  2530.0
강북구  159.0  217.0   4.0   5.0   6.0   7.0   672.0  1222.0  2482.0  2778.0
강서구  239.0  275.0  10.0  10.0  10.0   9.0  1070.0  1952.0  2768.0  3204.0
관악구  264.0  322.0  10.0  12.0   7.0   6.0   937.0  2103.0  2707.0  3235.0

#### 🔰 검거율 데이터 생성

- 하나의 컬럼을 다른 컬럼으로 나누기

In [27]:
crime_anal_gu["강도검거"] / crime_anal_gu["강도발생"]

구별
강남구     1.076923
강동구     0.928571
강북구     0.800000
강서구     1.000000
관악구     0.833333
광진구     0.545455
구로구     1.300000
금천구     1.000000
노원구     1.500000
도봉구     1.000000
동대문구    1.200000
동작구     1.000000
마포구     1.750000
서대문구    0.800000
서초구     0.769231
성동구     1.666667
성북구     1.000000
송파구     0.800000
양천구     1.000000
영등포구    0.736842
용산구     1.111111
은평구     0.777778
종로구     0.750000
중구      0.875000
중랑구     1.000000
dtype: float64

- 다수의 컬럼을 다른 컬럼으로 나누기

In [28]:
crime_anal_gu[["강도검거", "살인검거"]].div(crime_anal_gu["강도발생"], axis=0).head()

         강도검거      살인검거
구별
강남구  1.076923  0.128205
강동구  0.928571  0.357143
강북구  0.800000  1.200000
강서구  1.000000  1.000000
관악구  0.833333  0.583333

- 다수의 컬럼을 다수의 컬럼으로 각각 나누기

In [29]:
num = ["강간검거", "강도검거", "살인검거", "절도검거", "폭력검거"]
den = ["강간발생", "강도발생", "살인발생", "절도발생", "폭력발생"]

crime_anal_gu[num].div(crime_anal_gu[den].values).head()

         강간검거      강도검거      살인검거      절도검거      폭력검거
구별
강남구  0.800388  1.076923  1.000000  0.534709  0.881309
강동구  0.950000  0.928571  1.250000  0.514253  0.869960
강북구  0.732719  0.800000  0.857143  0.549918  0.893449
강서구  0.869091  1.000000  1.111111  0.548156  0.863920
관악구  0.819876  0.833333  1.166667  0.445554  0.836785

- "검거율" 컬럼 생성

In [30]:
target = ["강간검거율", "강도검거율", "살인검거율", "절도검거율", "폭력검거율"]

crime_anal_gu[target] = crime_anal_gu[num].div(crime_anal_gu[den].values) * 100
crime_anal_gu.head()

,강간검거,강간발생,강도검거,강도발생,살인검거,살인발생,절도검거,절도발생,폭력검거,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,,,,,,
강남구,413.0,516.0,42.0,39.0,5.0,5.0,1918.0,3587.0,3527.0,4002.0,80.038760,107.692308,100.000000,53.470867,88.130935
강동구,152.0,160.0,13.0,14.0,5.0,4.0,902.0,1754.0,2201.0,2530.0,95.000000,92.857143,125.000000,51.425314,86.996047
강북구,159.0,217.0,4.0,5.0,6.0,7.0,672.0,1222.0,2482.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
강서구,239.0,275.0,10.0,10.0,10.0,9.0,1070.0,1952.0,2768.0,3204.0,86.909091,100.000000,111.111111,54.815574,86.392010
관악구,264.0,322.0,10.0,12.0,7.0,6.0,937.0,2103.0,2707.0,3235.0,81.987578,83.333333,116.666667,44.555397,83.678516

- 필요 없는 컬럼 제거

In [31]:
crime_anal_gu.drop(["강간검거", "강도검거", "살인검거", "절도검거", "폭력검거"], axis=1, inplace=True)
crime_anal_gu.head()

,강간발생,강도발생,살인발생,절도발생,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.038760,107.692308,100.000000,53.470867,88.130935
강동구,160.0,14.0,4.0,1754.0,2530.0,95.000000,92.857143,125.000000,51.425314,86.996047
강북구,217.0,5.0,7.0,1222.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
강서구,275.0,10.0,9.0,1952.0,3204.0,86.909091,100.000000,111.111111,54.815574,86.392010
관악구,322.0,12.0,6.0,2103.0,3235.0,81.987578,83.333333,116.666667,44.555397,83.678516

👆 검거율 값 중 100이 넘는 것들이 있다.

- 검거율 100 이상의 수치는 강제로 100을 만들어 준다.

In [32]:
crime_anal_gu[crime_anal_gu[target] > 100]

,강간발생,강도발생,살인발생,절도발생,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,NaN,NaN,NaN,NaN,NaN,NaN,107.692308,NaN,NaN,NaN
강동구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,125.000000,NaN,NaN
강북구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
강서구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,111.111111,NaN,NaN
관악구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.666667,NaN,NaN
광진구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
구로구,NaN,NaN,NaN,NaN,NaN,NaN,130.000000,NaN,NaN,NaN
금천구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
노원구,NaN,NaN,NaN,NaN,NaN,NaN,150.000000,120.000000,NaN,NaN
도봉구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
동대문구,NaN,NaN,NaN,NaN,NaN,NaN,120.000000,NaN,NaN,NaN
동작구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
마포구,NaN,NaN,NaN,NaN,NaN,NaN,175.000000,NaN,NaN,NaN
서대문구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,116.666667,NaN,NaN
서초구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
성동구,NaN,NaN,NaN,NaN,NaN,NaN,166.666667,125.000000,NaN,NaN
성북구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
송파구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
양천구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
영등포구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
용산구,NaN,NaN,NaN,NaN,NaN,NaN,111.111111,NaN,NaN,NaN
은평구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
종로구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
중구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
중랑구,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [33]:
# 100보다 큰 숫자 찾아서 바꾸기

crime_anal_gu[crime_anal_gu[target] > 100] = 100
crime_anal_gu.head()

,강간발생,강도발생,살인발생,절도발생,폭력발생,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.038760,100.000000,100.000000,53.470867,88.130935
강동구,160.0,14.0,4.0,1754.0,2530.0,95.000000,92.857143,100.000000,51.425314,86.996047
강북구,217.0,5.0,7.0,1222.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
강서구,275.0,10.0,9.0,1952.0,3204.0,86.909091,100.000000,100.000000,54.815574,86.392010
관악구,322.0,12.0,6.0,2103.0,3235.0,81.987578,83.333333,100.000000,44.555397,83.678516

#### 🔰 컬럼명 변경

In [34]:
crime_anal_gu.rename(
	columns={
		"강간발생": "강간",
		"강도발생": "강도",		
		"살인발생": "살인",		
		"절도발생": "절도",		
		"폭력발생": "폭력",		
	},
	inplace=True
)
crime_anal_gu.head()

,강간,강도,살인,절도,폭력,강간검거율,강도검거율,살인검거율,절도검거율,폭력검거율
구별,,,,,,,,,,
강남구,516.0,39.0,5.0,3587.0,4002.0,80.038760,100.000000,100.000000,53.470867,88.130935
강동구,160.0,14.0,4.0,1754.0,2530.0,95.000000,92.857143,100.000000,51.425314,86.996047
강북구,217.0,5.0,7.0,1222.0,2778.0,73.271889,80.000000,85.714286,54.991817,89.344852
강서구,275.0,10.0,9.0,1952.0,3204.0,86.909091,100.000000,100.000000,54.815574,86.392010
관악구,322.0,12.0,6.0,2103.0,3235.0,81.987578,83.333333,100.000000,44.555397,83.678516

In [38]:
crime_anal_gu.to_csv("./result_data/04_crime_anal_gu.csv", encoding='utf-8')