# 분석 데이터 전처리

- 구별로 총 25개의 주유소 정보를 담은 엑셀 파일 읽어온다.

- 구별 데이터를 하나로 합친다.

In [1]:
import pandas as pd
import numpy as np
from glob import glob

### 🔰 `glob` 모듈

- !pip install glob(기본으로 설치되어 있음)

- 파일의 목록을 읽어오고 정리해주는 모듈이다.

- `glob()`

	- 파일 목록 한 번에 가져와 리스트로 반환한다.

In [2]:
glob("./result_data/지역_*.xls")

['./result_data\\지역_위치별(주유소) (1).xls',
 './result_data\\지역_위치별(주유소) (10).xls',
 './result_data\\지역_위치별(주유소) (11).xls',
 './result_data\\지역_위치별(주유소) (12).xls',
 './result_data\\지역_위치별(주유소) (13).xls',
 './result_data\\지역_위치별(주유소) (14).xls',
 './result_data\\지역_위치별(주유소) (15).xls',
 './result_data\\지역_위치별(주유소) (16).xls',
 './result_data\\지역_위치별(주유소) (17).xls',
 './result_data\\지역_위치별(주유소) (18).xls',
 './result_data\\지역_위치별(주유소) (19).xls',
 './result_data\\지역_위치별(주유소) (2).xls',
 './result_data\\지역_위치별(주유소) (20).xls',
 './result_data\\지역_위치별(주유소) (21).xls',
 './result_data\\지역_위치별(주유소) (22).xls',
 './result_data\\지역_위치별(주유소) (23).xls',
 './result_data\\지역_위치별(주유소) (24).xls',
 './result_data\\지역_위치별(주유소) (3).xls',
 './result_data\\지역_위치별(주유소) (4).xls',
 './result_data\\지역_위치별(주유소) (5).xls',
 './result_data\\지역_위치별(주유소) (6).xls',
 './result_data\\지역_위치별(주유소) (7).xls',
 './result_data\\지역_위치별(주유소) (8).xls',
 './result_data\\지역_위치별(주유소) (9).xls',
 './result_data\\지역_위치별(주유소).xls']

- 파일명 저장

In [3]:
oil_stations_files = glob("./result_data/지역_*.xls")
oil_stations_files[:5]

['./result_data\\지역_위치별(주유소) (1).xls',
 './result_data\\지역_위치별(주유소) (10).xls',
 './result_data\\지역_위치별(주유소) (11).xls',
 './result_data\\지역_위치별(주유소) (12).xls',
 './result_data\\지역_위치별(주유소) (13).xls']

### 🔰 DataFrame 생성

- 엑셀 파일 읽기

	- 일단 하나만 읽어본다.

	- 컬럼이 원하는 형태로 나오지 않는다.

	- 엑셀 파일을 열어보면 위에 두개의 빈 rows를 확인할 수 있다.

	- 읽어올 때 제외하고 읽어온다.

In [4]:
pd.read_excel(oil_stations_files[0]).tail(2)

,지역_위치별(주유소),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
14,서울특별시,천호현대주유소,서울 강동구 천중로 67 (천호동),HD현대오일뱅크,02-484-9323,N,-,1843,1743,-
15,서울특별시,광성주유소,서울 강동구 올림픽로 673 (천호동),S-OIL,02-470-5133,N,-,1968,1858,1800

In [5]:
tmp = pd.read_excel(oil_stations_files[0], header=2)
tmp.tail(2)

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
12,서울특별시,천호현대주유소,서울 강동구 천중로 67 (천호동),HD현대오일뱅크,02-484-9323,N,-,1843,1743,-
13,서울특별시,광성주유소,서울 강동구 올림픽로 673 (천호동),S-OIL,02-470-5133,N,-,1968,1858,1800

In [6]:
# 구별 전체 엑셀 파일 읽어오기

tmp_gu_df_raw = []

for file_name in oil_stations_files:
    tmp_gu_df = pd.read_excel(file_name, header=2)
    tmp_gu_df_raw.append(tmp_gu_df)
    
tmp_gu_df_raw

[       지역                    상호                            주소        상표  \
 0   서울특별시  재건에너지 재정제2주유소 고속셀프지점  서울특별시 강동구  천호대로 1246 (둔촌제2동)  HD현대오일뱅크
 1   서울특별시                구천면주유소         서울 강동구 구천면로 357 (암사동)  HD현대오일뱅크
 2   서울특별시           (주)소모 신월주유소        서울 강동구 양재대로 1323 (성내동)     GS칼텍스
 3   서울특별시          대성석유(주)길동주유소              서울 강동구 천호대로 1168     GS칼텍스
 4   서울특별시               방아다리주유소          서울 강동구 동남로 811 (명일동)     SK에너지
 5   서울특별시        (주)삼표에너지 고덕주유소           서울 강동구 고덕로 39 (암사동)     GS칼텍스
 6   서울특별시                 명일주유소          서울 강동구 고덕로 168 (명일동)     SK에너지
 7   서울특별시           (주)소모 성내주유소         서울 강동구 올림픽로 578 (성내동)     GS칼텍스
 8   서울특별시       (주)퍼스트오일 코알라주유소     서울특별시 강동구  올림픽로 556 (성내동)     S-OIL
 9   서울특별시              sk해뜨는주유소         서울 강동구  상일로 132 (강일동)     SK에너지
 10  서울특별시        지에스칼텍스㈜ 동서울주유소        서울 강동구 천호대로 1456 (상일동)     GS칼텍스
 11  서울특별시      주)지유에너지직영 오렌지주유소          서울 강동구 성안로 102 (성내동)     SK에너지
 12  서울특별시               천호현대주유소           서울 강동구 천중로 67 (천호동)  HD현대오일뱅크
 13  서울특별시                 광성주유소         서울 강동구 올림픽로 673 (천호동)     S-OIL

             전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0    02-487-2030    Y     -  1559  1469     -
 1    02-441-0536    N     -  1584  1495     -
 2   02-6956-6674    Y  1856  1636  1558  1590
 3    02-474-7222    N  1875  1636  1558  1600
 4    02-442-5145    Y     -  1665  1575  1500
 5    02-441-3327    Y  1865  1665  1585  1579
 6   02-3428-1739    Y  1895  1665  1585     -
 7    02-479-3838    Y     -  1688  1588     -
 8    02-484-1162    Y     -  1690  1590     -
 9    02-442-7801    Y  1929  1699  1609  1600
 10   02-426-5372    Y  1881  1711  1639     -
 11   02-484-6165    N  1954  1754  1654     -
 12   02-484-9323    N     -  1843  1743     -
 13   02-470-5133    N     -  1968  1858  1800  ,
        지역                  상호                       주소        상표  \
 0   서울특별시      (주)자연에너지 국민주유소  서울 동대문구 답십리로 223 (답십리동)  HD현대오일뱅크
 1   서울특별시            동서울고속주유소          서울 동대문구 한천로 414     SK에너지
 2   서울특별시               열린주유소    서울 동대문구 한천로 263 (휘경동)     S-OIL
 3   서울특별시             재정제2주유소    서울 동대문구 사가정로 90 (전농동)  HD현대오일뱅크
 4   서울특별시               재정주유소    서울 동대문구 전농로 121 (전농동)  HD현대오일뱅크
 5   서울특별시               풍한주유소          서울 동대문구 안암로 168     SK에너지
 6   서울특별시            (주)경동주유소    서울 동대문구 이문로 191 (이문동)     S-OIL
 7   서울특별시            (주)파랑에너지          서울 동대문구 망우로 126     GS칼텍스
 8   서울특별시       대성산업(주)동마장주유소   서울 동대문구 고산자로 405 (용두동)     GS칼텍스
 9   서울특별시         대성산업㈜청량리주유소   서울 동대문구 왕산로 289 (청량리동)     GS칼텍스
 10  서울특별시               삼영주유소   서울 동대문구 답십리로 258 (장안동)     SK에너지
 11  서울특별시               홍능주유소    서울 동대문구 홍릉로 87 (청량리동)     S-OIL
 12  서울특별시    (주)안국에너지 삼원셀프주유소     서울 동대문구 망우로 90 (휘경동)     SK에너지
 13  서울특별시          한영주유소 (한화)     서울 동대문구 망우로 38 (휘경동)  HD현대오일뱅크
 14  서울특별시  HD현대오일뱅크㈜직영 스피드주유소   서울 동대문구 천호대로 453 (장안동)  HD현대오일뱅크
 15  서울특별시     삼미상사(주)장안킹셀프주유소   서울 동대문구  한천로 100 (장안동)     SK에너지
 16  서울특별시             오동나무주유소   서울 동대문구  한천로 81 (답십리동)     S-OIL
 17  서울특별시              배봉로주유소       서울 동대문구 서울시립대로 108  HD현대오일뱅크

              전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0    02-2216-7155    Y  1750  1507  1417     -
 1     02-969-1144    Y  1750  1507  1417     -
 2    02-2215-6543    N     -  1527  1427     -
 3    02-2249-6682    Y     -  1529  1445     -
 4   070-8256-4617    Y  1799  1529  1445     -
 5     02-924-5189    N     -  1535  1455     -
 6     02-965-6006    Y     -  1555  1465  1500
 7    02-2242-5145    Y  1799  1559  1475  1400
 8     02-966-5451    Y  1759  1565  1485     -
 9     02-966-2714    Y     -  1565  1475     -
 10   02-2217-2018    N     -  1567  1477  1700
 11    02-966-9190    N     -  1575  1515  1500
 12   02-2244-1972    Y     -  1578  1498  1360
 13   02-2214-9890    N     -  1579  1539  1490
 14   02-2216-5151    N  1849  1589  1509     -
 15   02-2242-7115    Y     -  1637  1557     -
 16   02-2247-5132    N     -  1638  1548  1550
 17   02-2242-0556    Y     -  1655  1560     -  ,
       지역                    상호                      주소        상표         전화번호  \
 0  서울특별시       지에스칼텍스(주) 대방주유소        서울 동작구 여의대방로 214     GS칼텍스  02-826-5145
 1  서울특별시              창원이엔지주유소     서울 동작구 사당로 59 (상도동)  HD현대오일뱅크  02-825-5151
 2  서울특별시  HD현대오일뱅크㈜직영 신대방셀프주유소  서울 동작구 시흥대로 616 (신대방동)  HD현대오일뱅크  02-832-7926
 3  서울특별시                 매일주유소    서울 동작구 상도로 139 (상도동)     S-OIL  02-817-4085
 4  서울특별시   HD현대오일뱅크㈜직영 사당셀프주유소    서울 동작구 동작대로 73 (사당동)  HD현대오일뱅크  02-521-3618
 5  서울특별시       지에스칼텍스㈜직영 남성주유소   서울 동작구 동작대로 135 (사당동)     GS칼텍스  02-532-0606
 6  서울특별시  HD현대오일뱅크㈜직영 흑석동셀프주유소    서울 동작구 현충로 101 (흑석동)  HD현대오일뱅크  02-815-0724
 7  서울특별시     HD현대오일뱅크㈜직영 동작주유소    서울 동작구 상도로 403 (상도동)  HD현대오일뱅크  02-817-9179
 8  서울특별시                살피재주유소          서울 동작구 상도로 334     SK에너지  02-817-2559

   셀프여부 고급휘발유   휘발유    경유  실내등유
 0    N  1759  1559  1469  1400
 1    Y     -  1575  1475     -
 2    Y  1809  1579  1484     -
 3    Y     -  1599  1579  1650
 4    Y  1919  1599  1559     -
 5    Y  1804  1604  1564     -
 6    Y  1829  1604  1569     -
 7    N  1839  1614  1574     -
 8    N     -  1785  1695     -  ,
        지역               상호                        주소        상표           전화번호  \
 0   서울특별시  (주)타이거통상 월드컵주유소  서울 마포구 월드컵북로 170 (성산제2동)     S-OIL    02-373-3314
 1   서울특별시          마포시엠주유소           서울 마포구 월드컵북로 62     SK에너지    02-338-9447
 2   서울특별시            청원주유소    서울 마포구 월드컵북로 113 (성산동)  HD현대오일뱅크    02-325-5533
 3   서울특별시        성산대교셀프주유소            서울 마포구 성산로 144  HD현대오일뱅크    02-323-0078
 4   서울특별시  (주)안국에너지 망원동주유소     서울 마포구 월드컵로 119 (망원동)     SK에너지    02-334-0917
 5   서울특별시   에쓰오일(주) 염리동주유소      서울 마포구 백범로 126 (염리동)     S-OIL   02-3272-5155
 6   서울특별시            용강주유소            서울 마포구 토정로 258     S-OIL  070-7795-4800
 7   서울특별시    (주)만성상사 대흥주유소       서울 마포구 대흥로 61 (대흥동)     SK에너지   02-3273-5151
 8   서울특별시         에스에스오토셀프       서울 마포구 서강로 76 (창전동)  HD현대오일뱅크    02-336-5185
 9   서울특별시     에쓰오일(주)마포주유소     서울 마포구 마포대로 186 (공덕동)     S-OIL    02-711-5189
 10  서울특별시      SK에너지 양지주유소      서울 마포구 마포대로 69 (도화동)     SK에너지    02-706-8955
 11  서울특별시   SK에너지(주) 안국주유소             서울 마포구 양화로 33     SK에너지   02-3144-1197

    셀프여부 고급휘발유   휘발유    경유  실내등유
 0     Y  1779  1499  1459     -
 1     N     -  1509  1469     -
 2     Y  1799  1529  1499     -
 3     Y     -  1529  1499  1585
 4     N     -  1588  1528     -
 5     Y     -  1589  1549     -
 6     N     -  1609  1569  1650
 7     N  2149  1619  1579  1695
 8     Y  2159  1629  1579     -
 9     Y  1729  1639  1539     -
 10    N  1879  1659  1619     -
 11    N  1879  1659  1614     -  ,
        지역                  상호                            주소        상표  \
 0   서울특별시     (주)미래아스팔트 신우주유소          서울 서대문구 가좌로 106(홍은동)     S-OIL
 1   서울특별시        (주)가재울뉴타운주유소              서울 서대문구 모래내로 205  HD현대오일뱅크
 2   서울특별시               남정주유소       서울 서대문구 모래내로 243 (남가좌동)     GS칼텍스
 3   서울특별시       (주)창원이엔지 홍제지점         서울 서대문구 통일로 455 (홍제동)  HD현대오일뱅크
 4   서울특별시   (주)한화미 구도일주유소 두꺼비               서울 서대문구 성산로 312     S-OIL
 5   서울특별시   HD현대오일뱅크㈜직영 연세주유소               서울 서대문구 연희로 184  HD현대오일뱅크
 6   서울특별시     지에스칼텍스(주)홍제동주유소               서울 서대문구 통일로 372     GS칼텍스
 7   서울특별시  HD현대오일뱅크㈜직영 독립문주유소         서울 서대문구 통일로 384 (홍제동)  HD현대오일뱅크
 8   서울특별시    (주)안국에너지 삼보셀프주유소          서울 서대문구 연희로 78 (연희동)     SK에너지
 9   서울특별시             행촌제2주유소         서울 서대문구 성산로 490 (대신동)     SK에너지
 10  서울특별시         중앙에너비스 동교지점          서울 서대문구 연희로 12 (창천동)     SK에너지
 11  서울특별시      ㈜우남에너지 문화사랑주유소         서울 서대문구 세검정로 87 (홍제동)     S-OIL
 12  서울특별시        삼미상사(주)서부주유소               서울 서대문구 성산로 255     SK에너지
 13  서울특별시               연희주유소  서울 서대문구 연희로 129 (연희동 89-7번지)     SK에너지
 14  서울특별시               광호주유소         서울 서대문구 연희로 266 (홍은동)     SK에너지

              전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0     02-304-5522    Y     -  1529  1489     -
 1   070-8879-7864    Y     -  1529  1459     -
 2     02-305-9828    N     -  1538  1488  1750
 3     02-379-0753    N     -  1539  1479  1800
 4     02-336-0611    Y  1799  1539  1499     -
 5     02-337-8220    Y  1828  1544  1489     -
 6     02-736-3708    Y  1799  1549  1499     -
 7     02-735-0333    N  1888  1549  1489     -
 8     02-336-6151    Y  1788  1569  1498     -
 9     02-365-5189    Y  1799  1569  1498     -
 10  070-8707-4568    Y  1838  1575  1495     -
 11    02-395-4300    Y     -  1589  1559  1650
 12    02-334-4919    Y     -  1595  1539     -
 13    02-338-8045    N  1898  1598  1558     -
 14    02-395-7236    N     -  1598  1558     -  ,
        지역                    상호                          주소        상표  \
 0   서울특별시              만남의광장주유소        서울 서초구 양재대로12길 73-71    알뜰(ex)
 1   서울특별시               양재최고주유소         서울 서초구 매헌로 72 (양재동)     S-OIL
 2   서울특별시        (주)대농석유 남태령주유소       서울 서초구 과천대로 838 (방배동)     SK에너지
 3   서울특별시            서초하이웨이 주유소        서울 서초구 양재대로2길 100-30     S-OIL
 4   서울특별시                헌릉로주유소        서울 서초구 헌릉로 177 (내곡동)     S-OIL
 5   서울특별시         에너지 플러스 허브 내곡              서울 서초구 헌릉로 210     GS칼텍스
 6   서울특별시        지에스칼텍스(주)선천주유소       서울 서초구 동작대로 206 (방배동)     GS칼텍스
 7   서울특별시               태봉셀프주유소        서울 서초구 태봉로 117 (우면동)     SK에너지
 8   서울특별시                신반포주유소        서울 서초구 사평대로 94 (반포동)     SK에너지
 9   서울특별시                 한독주유소        서울 서초구 방배로 218 (방배동)     GS칼텍스
 10  서울특별시       대성산업(주)직영 강남주유소       서울 서초구 반포대로 284 (반포동)     GS칼텍스
 11  서울특별시    HD현대오일뱅크㈜직영 팔레스주유소       서울 서초구 사평대로 136 (반포동)  HD현대오일뱅크
 12  서울특별시     에쓰오일(주)직영 오토테크주유소    서울특별시 서초구  효령로 356 (서초동)     S-OIL
 13  서울특별시        극동유화(주) 전당앞주유소     서울 서초구 남부순환로 2391 (서초동)     S-OIL
 14  서울특별시         (주)한미석유 서초주유소        서울 서초구 반포대로 64 (서초동)     GS칼텍스
 15  서울특별시        에너지플러스허브 삼방주유소       서울 서초구 사평대로 364 (서초동)     GS칼텍스
 16  서울특별시    HD현대오일뱅크㈜직영 사평로주유소       서울 서초구 사평대로 350 (서초동)  HD현대오일뱅크
 17  서울특별시               반포그린주유소      서울 서초구 서초중앙로 239 (반포동)     GS칼텍스
 18  서울특별시              서초꽃마을주유소        서울 서초구 반포대로 69 (서초동)     GS칼텍스
 19  서울특별시               말죽거리주유소     서울 서초구 남부순환로 2650 (양재동)     GS칼텍스
 20  서울특별시                 양재주유소             서울 서초구 바우뫼로 178     SK에너지
 21  서울특별시   HD현대오일뱅크㈜직영 양재현대주유소                서울 서초구 마방로 6  HD현대오일뱅크
 22  서울특별시   HD현대오일뱅크㈜직영 방배현대주유소       서울 서초구 동작대로 182 (방배동)  HD현대오일뱅크
 23  서울특별시   HD현대오일뱅크㈜직영 서초제일주유소       서울 서초구 사임당로 116 (서초동)  HD현대오일뱅크
 24  서울특별시          대성석유(주)연일주유소           서울 서초구 남부순환로 2451     GS칼텍스
 25  서울특별시  대성산업(주)직영 터미널(고속)주유소       서울 서초구 신반포로 222 (반포동)     GS칼텍스
 26  서울특별시          대신석유(주)대우주유소       서울 서초구 양재대로 173 (양재동)     SK에너지
 27  서울특별시       지에스칼텍스(주)남서울주유소        서울 서초구 나루터로 83 (잠원동)     GS칼텍스
 28  서울특별시                방배동주유소         서울 서초구 효령로 29 (방배동)     SK에너지
 29  서울특별시            대신석유㈜서원주유소       서울 서초구 반포대로 142 (서초동)     SK에너지
 30  서울특별시        (주)선문에너지 중앙주유소  서울특별시 서초구  바우뫼로 219 (양재1동)     S-OIL

             전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0    02-573-7430    Y     -  1509  1417     -
 1   02-2057-5189    N     -  1585  1515     -
 2    02-587-0895    Y     -  1585  1485     -
 3    02-577-5151    Y  1767  1597  1527     -
 4   02-2058-3224    Y  1799  1599  1529  1550
 5    02-573-7878    Y  1799  1599  1529     -
 6    02-592-4915    N  1754  1604  1564     -
 7    02-571-8000    Y     -  1607  1535     -
 8    02-533-5151    Y  1819  1609  1558     -
 9   02-3477-6127    Y  1819  1609  1558     -
 10   02-594-5987    Y  1819  1609  1558     -
 11   02-720-0020    N  1820  1610  1559     -
 12   02-585-5189    Y  1815  1615  1535     -
 13  02-6080-0516    Y  1815  1615  1535     -
 14   02-582-5198    Y  1825  1615  1535     -
 15   02-536-5145    Y  1816  1616  1589     -
 16  02-3481-2513    N  1840  1616  1589     -
 17   02-532-5147    Y  1816  1616  1589     -
 18   02-523-5551    Y  1835  1625  1545     -
 19   02-579-9933    N     -  1626  1546  1650
 20   02-577-1621    N  1839  1629  1554     -
 21   02-579-8429    N  1839  1629  1554  1570
 22   02-534-0051    N  1840  1632  1570  1620
 23   02-587-6080    N  1840  1632  1581     -
 24  02-3471-5151    N  1846  1636  1545  1600
 25   02-535-3001    N  1826  1645  1585  1650
 26   02-572-0567    Y     -  1649  1567     -
 27   02-542-1517    N  1879  1699  1679     -
 28   02-584-2086    N  1998  1893  1796     -
 29   02-599-3657    N  2068  1968  1868     -
 30   02-575-5110    N  2394  2168  1989  1780  ,
        지역                   상호                       주소        상표  \
 0   서울특별시             KLP제2주유소     서울 성동구 동일로 249 (송정동)  HD현대오일뱅크
 1   서울특별시          (주)서울에너지 직영    서울 성동구 천호대로 324 (용답동)     S-OIL
 2   서울특별시                정호주유소    서울 성동구 고산자로 307 (마장동)      자가상표
 3   서울특별시       지에스칼텍스㈜ 도루코주유소          서울 성동구 아차산로 180     GS칼텍스
 4   서울특별시  HD현대오일뱅크㈜직영 성동셀프주유소     서울 성동구 마장로 311 (마장동)  HD현대오일뱅크
 5   서울특별시               아이콘주유소    서울 성동구 고산자로 273 (도선동)     S-OIL
 6   서울특별시      SK에너지(주) 군자동주유소    서울 성동구 천호대로 446 (용답동)     SK에너지
 7   서울특별시                삼우주유소          서울 성동구 천호대로 392     SK에너지
 8   서울특별시       SK에너지(주) 성수주유소   서울 성동구 뚝섬로 352 (성수동1가)     SK에너지
 9   서울특별시     SK KH에너지 성수만세주유소          서울 성동구 왕십리로 109     SK에너지
 10  서울특별시             SK세원2주유소  서울 성동구 광나루로 184 (성수동1가)     SK에너지
 11  서울특별시                금호주유소    서울 성동구 금호로 39 (금호동4가)     GS칼텍스
 12  서울특별시                동일주유소  서울 성동구 광나루로 254 (성수동2가)  HD현대오일뱅크
 13  서울특별시               청계로주유소  서울 성동구 청계천로 454 (하왕십리동)     SK에너지
 14  서울특별시        (주)옥수하이웨이스테이션    서울 성동구 독서당로 168 (옥수동)     GS칼텍스

             전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0    02-465-5182    Y     -  1524  1444     -
 1   02-3390-4338    Y     -  1529  1449     -
 2   02-2297-9442    N     -  1558  1478     -
 3    02-463-6919    Y  1816  1564  1484  1655
 4   02-2299-7333    Y  1859  1575  1500     -
 5   02-2291-5189    Y  1798  1588  1498     -
 6   02-2244-4945    N  1839  1589  1509     -
 7   02-2245-8974    N     -  1697  1697     -
 8    02-467-7240    N  1878  1748  1695     -
 9    02-499-8223    Y  1898  1758  1695     -
 10   02-462-5665    N  2145  1760  1687     -
 11  02-2297-0066    N  2095  1896  1797  1890
 12   02-461-7100    N  2269  1967  1875  1775
 13  02-2294-4225    N     -  1995  1945  1895
 14  02-2282-5151    N  2298  2148  2098     -  ,
        지역                   상호                         주소        상표  \
 0   서울특별시                원천주유소      서울 성북구 돌곶이로 142 (장위동)     GS칼텍스
 1   서울특별시    이케이에너지(주) 강산제2주유소             서울 성북구 보국문로 52  HD현대오일뱅크
 2   서울특별시       (주)삼표에너지 정릉주유소       서울 성북구 보국문로 35 (정릉동)     GS칼텍스
 3   서울특별시        이케이에너지㈜ 강산주유소      서울 성북구 보문로 27 (보문동7가)     GS칼텍스
 4   서울특별시                장위주유소      서울 성북구 화랑로 110 (하월곡동)     S-OIL
 5   서울특별시           장삼 쌍둥이 주유소       서울 성북구 한천로 612 (장위동)  HD현대오일뱅크
 6   서울특별시             (주)성북주유소             서울 성북구 보문로 142  HD현대오일뱅크
 7   서울특별시          중앙에너비스 종암지점              서울 성북구 종암로 58     SK에너지
 8   서울특별시                우리주유소             서울 성북구 화랑로 292     SK에너지
 9   서울특별시         ㈜명연에너지 효성주유소              서울 성북구 화랑로 27     GS칼텍스
 10  서울특별시               신동방주유소        서울 성북구 월계로 84 (장위동)     S-OIL
 11  서울특별시      (주)신용 구도일주유소화랑로             서울 성북구 화랑로 174     S-OIL
 12  서울특별시      지에스칼텍스(주) 종암주유소       서울 성북구 종암로 145 (종암동)     GS칼텍스
 13  서울특별시     SK에너지(주) 드림랜드주유소       서울 성북구 월계로 128 (장위동)     SK에너지
 14  서울특별시  HD현대오일뱅크㈜직영 고대셀프주유소        서울 성북구 종암로 12 (종암동)  HD현대오일뱅크
 15  서울특별시  HD현대오일뱅크㈜직영 북악셀프주유소       서울 성북구 정릉로 218 (정릉동)  HD현대오일뱅크
 16  서울특별시                동일주유소  서울특별시 성북구  보문로 85 (보문동5가)     S-OIL
 17  서울특별시                신방주유소     서울 성북구 안암로 111 (안암동5가)     S-OIL
 18  서울특별시         재정제2주유소 길음지점        서울 성북구 삼양로 78 (길음동)  HD현대오일뱅크
 19  서울특별시   HD현대오일뱅크㈜직영 아리랑주유소       서울 성북구 아리랑로 96 (정릉동)  HD현대오일뱅크
 20  서울특별시        지에스칼텍스㈜ 화랑주유소             서울 성북구 화랑로 185     GS칼텍스
 21  서울특별시                삼선주유소            서울 성북구 창경궁로 324     S-OIL
 22  서울특별시        지에스칼텍스㈜ 세창주유소            서울 성북구 동소문로 323     GS칼텍스

              전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0   070-4063-1057    Y     -  1503  1413     -
 1     02-942-1448    Y  1765  1505  1415     -
 2     02-914-6556    Y  1765  1505  1415  1550
 3     02-953-1448    Y     -  1505  1415  1300
 4    02-6498-5189    Y     -  1525  1455     -
 5     02-909-0314    Y     -  1525  1455     -
 6     02-928-4900    Y     -  1535  1465     -
 7   070-8707-4565    Y     -  1535  1455     -
 8     02-969-5185    Y     -  1544  1465     -
 9     02-942-5150    Y  1998  1545  1515     -
 10    02-918-5151    Y  1869  1545  1455     -
 11    02-963-0051    Y  1843  1553  1473  1450
 12    02-921-7785    Y  1805  1555  1465     -
 13    02-916-9906    N  1859  1555  1475  1520
 14    02-912-5151    Y     -  1555  1465     -
 15    02-911-5189    Y  2267  1557  1465     -
 16    02-923-8484    Y  1895  1559  1519     -
 17    02-922-5151    N     -  1559  1479     -
 18    02-980-1311    N     -  1569  1499  1450
 19    02-941-5189    N  1925  1570  1529     -
 20    02-942-5152    N     -  1604  1564  1381
 21    02-766-5105    Y  1977  1675  1495     -
 22    02-988-2491    Y  1970  1714  1624  1351  ,
        지역                    상호                        주소        상표  \
 0   서울특별시     지에스칼텍스(주)스마트위례주유소     서울 송파구 위례중앙로 43 (장지동)     GS칼텍스
 1   서울특별시                 상아주유소             서울 송파구 거마로 82     S-OIL
 2   서울특별시     지에스칼텍스(주)가든파이브주유소           서울 송파구 탄천동로 740     GS칼텍스
 3   서울특별시               위례제일주유소           서울 송파구 위례서로 260     S-OIL
 4   서울특별시         (주)신화에너지 서울지점       서울 송파구 가락로 47 (석촌동)     SK에너지
 5   서울특별시   HD현대오일뱅크㈜직영 잠실셀프주유소     서울 송파구 송파대로 397 (석촌동)  HD현대오일뱅크
 6   서울특별시                남성대주유소      서울 송파구 송파대로 52 (장지동)     SK에너지
 7   서울특별시                 삼화주유소          서울 송파구 백제고분로 125     GS칼텍스
 8   서울특별시               위례드림주유소         서울시 송파구  위례중앙로 10     S-OIL
 9   서울특별시     (유)호림플러스홀딩스 남성주유소    서울 송파구 백제고분로 474 (방이동)  HD현대오일뱅크
 10  서울특별시        한강에너지(주)퍼스트주유소      서울 송파구 삼학사로 22 (석촌동)     SK에너지
 11  서울특별시                 방이주유소  서울 송파구 위례성대로12길 38 (방이동)     SK에너지
 12  서울특별시       (주)삼표에너지 아시아주유소      서울 송파구 도곡로 438 (잠실동)     GS칼텍스
 13  서울특별시     지에스이앤알 직영 송파제일주유소      서울 송파구 삼학사로 50 (석촌동)  HD현대오일뱅크
 14  서울특별시                 대성주유소      서울 송파구 마천로 230 (마천동)     SK에너지
 15  서울특별시              백제고분로주유소      서울 송파구 오금로 143 (방이동)     SK에너지
 16  서울특별시              (주)유진주유소      서울 송파구 동남로 325 (오금동)     SK에너지
 17  서울특별시                 완불주유소       서울 송파구 송파대로 3 (장지동)     SK에너지
 18  서울특별시              (주)잠실에너지     서울 송파구 송파대로 442 (송파동)     S-OIL
 19  서울특별시             (주)정직한주유소      서울 송파구 오금로 455 (거여동)  HD현대오일뱅크
 20  서울특별시             제트라인DM주유소      서울 송파구 중대로 183 (가락동)  HD현대오일뱅크
 21  서울특별시          대성석유(주)석촌주유소          서울 송파구 백제고분로 289     GS칼텍스
 22  서울특별시        (주)삼표에너지 우리주유소            서울 송파구 동남로 153     GS칼텍스
 23  서울특별시                 송파주유소       서울 송파구 송이로 28 (송파동)     GS칼텍스
 24  서울특별시       (주)삼표에너지 훼미리주유소       서울 송파구 중대로 58 (문정동)     GS칼텍스
 25  서울특별시         (주)퍼스트오일서울주유소            서울 송파구 문정로 153     S-OIL
 26  서울특별시  HD현대오일뱅크㈜직영 올림픽셀프주유소    서울 송파구 위례성대로 188 (오금동)  HD현대오일뱅크
 27  서울특별시          대신석유(주)진양주유소     서울 송파구 올림픽로 499 (풍납동)     SK에너지

             전화번호 셀프여부 고급휘발유   휘발유    경유  실내등유
 0    02-409-5185    Y  1763  1563  1474     -
 1    02-409-8251    Y     -  1563  1474  1500
 2    02-409-5145    Y  1763  1563  1474     -
 3    02-408-9951    Y     -  1563  1474     -
 4   02-2202-8484    Y     -  1573  1485     -
 5    02-417-7111    Y  1783  1573  1483  1560
 6    02-409-2211    Y     -  1573  1484  1600
 7   02-2203-2280    Y  1783  1573  1485     -
 8    02-404-5189    Y  1758  1573  1484     -
 9    02-423-5128    N     -  1573  1498     -
 10   02-422-2834    Y  1783  1573  1485     -
 11   02-424-3051    N     -  1573  1483     -
 12   02-416-1911    Y  1803  1573  1495     -
 13   02-424-2900    Y     -  1573  1485     -
 14   02-431-1991    N     -  1578  1508  1500
 15  02-2202-4050    Y  1783  1583  1513     -
 16   02-406-3956    N     -  1583  1513     -
 17  02-3402-2900    Y  1791  1590  1542     -
 18   02-414-5010    Y  1783  1595  1514     -
 19   02-406-4634    Y     -  1597  1537     -
 20   02-430-5151    N     -  1598  1538     -
 21   02-421-0051    N  1878  1617  1527  1600

- `concat()`

	- concatenation, 연결·연쇄·연속
	
	- DataFrame의 구조와 형식이 동일하면 연달아 이어 붙이기가 가능하다.

In [7]:
stations_raw = pd.concat(tmp_gu_df_raw)
stations_raw

,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
0,서울특별시,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),HD현대오일뱅크,02-487-2030,Y,-,1559,1469,-
1,서울특별시,구천면주유소,서울 강동구 구천면로 357 (암사동),HD현대오일뱅크,02-441-0536,N,-,1584,1495,-
2,서울특별시,(주)소모 신월주유소,서울 강동구 양재대로 1323 (성내동),GS칼텍스,02-6956-6674,Y,1856,1636,1558,1590
3,서울특별시,대성석유(주)길동주유소,서울 강동구 천호대로 1168,GS칼텍스,02-474-7222,N,1875,1636,1558,1600
4,서울특별시,방아다리주유소,서울 강동구 동남로 811 (명일동),SK에너지,02-442-5145,Y,-,1665,1575,1500
...,...,...,...,...,...,...,...,...,...,...
27,서울특별시,대청주유소,서울 강남구 개포로 654 (일원동),SK에너지,02-445-5500,N,2489,2195,2086,1846
28,서울특별시,SK논현주유소,서울 강남구 논현로 747 (논현동),SK에너지,02-511-0955,N,2630,2395,2295,1798
29,서울특별시,(주)제이제이네트웍스 제이제이주유소,서울 강남구 언주로 716,HD현대오일뱅크,02-518-5631,N,2690,2490,2380,-
30,서울특별시,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),GS칼텍스,02-518-5141,N,2838,2598,2560,1850
31,서울특별시,대양산업(주) 개포주유소,서울 강남구 양재대로 339,GS칼텍스,02-573-9031,Y,-,-,1698,1650

👆 여러 개의 DataFrame을 합치면서 인덱스값이 제대로 표시되지 않음.

- 인덱스를 다시 재정렬 해준다.

In [8]:
stations_raw.reset_index(inplace=True)
stations_raw.tail()

,index,지역,상호,주소,상표,전화번호,셀프여부,고급휘발유,휘발유,경유,실내등유
434,27,서울특별시,대청주유소,서울 강남구 개포로 654 (일원동),SK에너지,02-445-5500,N,2489,2195,2086,1846
435,28,서울특별시,SK논현주유소,서울 강남구 논현로 747 (논현동),SK에너지,02-511-0955,N,2630,2395,2295,1798
436,29,서울특별시,(주)제이제이네트웍스 제이제이주유소,서울 강남구 언주로 716,HD현대오일뱅크,02-518-5631,N,2690,2490,2380,-
437,30,서울특별시,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),GS칼텍스,02-518-5141,N,2838,2598,2560,1850
438,31,서울특별시,대양산업(주) 개포주유소,서울 강남구 양재대로 339,GS칼텍스,02-573-9031,Y,-,-,1698,1650

In [9]:
stations_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 11 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   index   439 non-null    int64
 1   지역      439 non-null    object
 2   상호      439 non-null    object
 3   주소      439 non-null    object
 4   상표      439 non-null    object
 5   전화번호    439 non-null    object
 6   셀프여부    439 non-null    object
 7   고급휘발유   439 non-null    object
 8   휘발유     439 non-null    object
 9   경유      439 non-null    int64
 10  실내등유    439 non-null    object
dtypes: int64(2), object(9)
memory usage: 37.9+ KB

### 🔰 DataFrame 편집

In [10]:
stations_raw.columns

Index(['index', '지역', '상호', '주소', '상표', '전화번호', '셀프여부', '고급휘발유', '휘발유', '경유',
       '실내등유'],
      dtype='object')

- 필요한 컬럼 데이터만 추려서 새로운 DataFrame 만들기

In [11]:
stations = pd.DataFrame({
	"상호": stations_raw["상호"],
	"주소": stations_raw["주소"],
	"가격": stations_raw["휘발유"],
	"셀프": stations_raw["셀프여부"],
	"상표": stations_raw["상표"]
})
stations.tail()

                      상호                     주소    가격 셀프        상표
434                대청주유소   서울 강남구 개포로 654 (일원동)  2195  N     SK에너지
435              SK논현주유소   서울 강남구 논현로 747 (논현동)  2395  N     SK에너지
436  (주)제이제이네트웍스 제이제이주유소         서울 강남구 언주로 716  2490  N  HD현대오일뱅크
437       (주)만정에너지 삼보주유소  서울 강남구 봉은사로 433 (삼성동)  2598  N     GS칼텍스
438        대양산업(주) 개포주유소        서울 강남구 양재대로 339     -  Y     GS칼텍스

- "주소"에서 구 이름 추출하기

In [ ]:
for each_address in stations["주소"]:
    print(each_address.split())

In [13]:
for each_address in stations["주소"]:
    print(each_address.split()[1])

강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
강동구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동대문구
동작구
동작구
동작구
동작구
동작구
동작구
동작구
동작구
동작구
마포구
마포구
마포구
마포구
마포구
마포구
마포구
마포구
마포구
마포구
마포구
마포구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서대문구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
서초구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성동구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
성북구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
송파구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
양천구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
영등포구
강북구
강북구
강북구
강북구
강북구
강북구
강북구
강북구
강북구
강북구
강북구
강북구
용산구
용산구
용산구
용산구
용산구
용산구
용산구
용산구
용산구
용산구
용산구
용산구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
은평구
종로구
종로구
종로구
종로구
종로구
종로구
종로구
종로구
종로구
중구
중구
중구
중구
중구
중구
중구
중구
중구
중구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
중랑구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
강서구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
관악구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
광진구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
구로구
금천구
금천구
금천구
금천구
금천구
금천구
금천구
금천구
금천구
금천구
금천구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
노원구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
도봉구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구
강남구

In [14]:
# means_1.
stations["구"] = [each_address.split()[1] for each_address in stations["주소"]]
stations

,상호,주소,가격,셀프,상표,구
0,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),1559,Y,HD현대오일뱅크,강동구
1,구천면주유소,서울 강동구 구천면로 357 (암사동),1584,N,HD현대오일뱅크,강동구
2,(주)소모 신월주유소,서울 강동구 양재대로 1323 (성내동),1636,Y,GS칼텍스,강동구
3,대성석유(주)길동주유소,서울 강동구 천호대로 1168,1636,N,GS칼텍스,강동구
4,방아다리주유소,서울 강동구 동남로 811 (명일동),1665,Y,SK에너지,강동구
...,...,...,...,...,...,...
434,대청주유소,서울 강남구 개포로 654 (일원동),2195,N,SK에너지,강남구
435,SK논현주유소,서울 강남구 논현로 747 (논현동),2395,N,SK에너지,강남구
436,(주)제이제이네트웍스 제이제이주유소,서울 강남구 언주로 716,2490,N,HD현대오일뱅크,강남구
437,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),2598,N,GS칼텍스,강남구
438,대양산업(주) 개포주유소,서울 강남구 양재대로 339,-,Y,GS칼텍스,강남구

In [15]:
# means_2.
stations["Gu"] = stations["주소"].apply(lambda addr: addr.split()[1])
stations

,상호,주소,가격,셀프,상표,구,Gu
0,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),1559,Y,HD현대오일뱅크,강동구,강동구
1,구천면주유소,서울 강동구 구천면로 357 (암사동),1584,N,HD현대오일뱅크,강동구,강동구
2,(주)소모 신월주유소,서울 강동구 양재대로 1323 (성내동),1636,Y,GS칼텍스,강동구,강동구
3,대성석유(주)길동주유소,서울 강동구 천호대로 1168,1636,N,GS칼텍스,강동구,강동구
4,방아다리주유소,서울 강동구 동남로 811 (명일동),1665,Y,SK에너지,강동구,강동구
...,...,...,...,...,...,...,...
434,대청주유소,서울 강남구 개포로 654 (일원동),2195,N,SK에너지,강남구,강남구
435,SK논현주유소,서울 강남구 논현로 747 (논현동),2395,N,SK에너지,강남구,강남구
436,(주)제이제이네트웍스 제이제이주유소,서울 강남구 언주로 716,2490,N,HD현대오일뱅크,강남구,강남구
437,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),2598,N,GS칼텍스,강남구,강남구
438,대양산업(주) 개포주유소,서울 강남구 양재대로 339,-,Y,GS칼텍스,강남구,강남구

In [16]:
stations["구"].unique(), len(stations["구"].unique())

(array(['강동구', '동대문구', '동작구', '마포구', '서대문구', '서초구', '성동구', '성북구', '송파구',
        '양천구', '영등포구', '강북구', '용산구', '은평구', '종로구', '중구', '중랑구', '강서구',
        '관악구', '광진구', '구로구', '금천구', '노원구', '도봉구', '강남구'], dtype=object),
 25)

- `astype()` : 데이터 형변환

	- "가격" 데이터 변환: object --> float

In [17]:
stations.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 439 entries, 0 to 438
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   상호      439 non-null    object
 1   주소      439 non-null    object
 2   가격      439 non-null    object
 3   셀프      439 non-null    object
 4   상표      439 non-null    object
 5   구       439 non-null    object
 6   Gu      439 non-null    object
dtypes: object(7)
memory usage: 24.1+ KB

In [18]:
stations["가격"] = stations["가격"].astype("float")

ValueError: could not convert string to float: '-'

👆 "가격" value에 존재하는 '-'를 float으로 형변환 할 수 없어 오류 발생

- 가격 정보 없는 주유소 확인

In [19]:
stations[stations["가격"] == "-"]

                상호               주소 가격 셀프     상표    구   Gu
438  대양산업(주) 개포주유소  서울 강남구 양재대로 339  -  Y  GS칼텍스  강남구  강남구

In [ ]:
# case_1. 가격 정보가 있는 주유소만 사용
stations = stations[stations["가격"] != "-"]

In [20]:
# case_2. '-'을 NaN으로 바꾼 후 NaN만 지우기
stations[["가격"]] = stations[["가격"]].applymap(lambda val: np.nan if val == '-' else val)
stations.tail()

                      상호                     주소    가격 셀프        상표    구   Gu
434                대청주유소   서울 강남구 개포로 654 (일원동)  2195  N     SK에너지  강남구  강남구
435              SK논현주유소   서울 강남구 논현로 747 (논현동)  2395  N     SK에너지  강남구  강남구
436  (주)제이제이네트웍스 제이제이주유소         서울 강남구 언주로 716  2490  N  HD현대오일뱅크  강남구  강남구
437       (주)만정에너지 삼보주유소  서울 강남구 봉은사로 433 (삼성동)  2598  N     GS칼텍스  강남구  강남구
438        대양산업(주) 개포주유소        서울 강남구 양재대로 339   NaN  Y     GS칼텍스  강남구  강남구

In [21]:
stations.dropna(axis=0).tail()

                      상호                     주소    가격 셀프        상표    구   Gu
433        ㈜새서울석유 새서울주유소        서울 강남구 압구정로 154  2158  N  HD현대오일뱅크  강남구  강남구
434                대청주유소   서울 강남구 개포로 654 (일원동)  2195  N     SK에너지  강남구  강남구
435              SK논현주유소   서울 강남구 논현로 747 (논현동)  2395  N     SK에너지  강남구  강남구
436  (주)제이제이네트웍스 제이제이주유소         서울 강남구 언주로 716  2490  N  HD현대오일뱅크  강남구  강남구
437       (주)만정에너지 삼보주유소  서울 강남구 봉은사로 433 (삼성동)  2598  N     GS칼텍스  강남구  강남구

In [22]:
stations.dropna(axis=0, inplace=True)
stations.tail()

                      상호                     주소    가격 셀프        상표    구   Gu
433        ㈜새서울석유 새서울주유소        서울 강남구 압구정로 154  2158  N  HD현대오일뱅크  강남구  강남구
434                대청주유소   서울 강남구 개포로 654 (일원동)  2195  N     SK에너지  강남구  강남구
435              SK논현주유소   서울 강남구 논현로 747 (논현동)  2395  N     SK에너지  강남구  강남구
436  (주)제이제이네트웍스 제이제이주유소         서울 강남구 언주로 716  2490  N  HD현대오일뱅크  강남구  강남구
437       (주)만정에너지 삼보주유소  서울 강남구 봉은사로 433 (삼성동)  2598  N     GS칼텍스  강남구  강남구

In [24]:
stations[stations["가격"] == "-"]

Empty DataFrame
Columns: [상호, 주소, 가격, 셀프, 상표, 구, Gu]
Index: []

In [25]:
stations["가격"] = stations["가격"].astype("float")

In [26]:
stations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 438 entries, 0 to 437
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   상호      438 non-null    object
 1   주소      438 non-null    object
 2   가격      438 non-null    float64
 3   셀프      438 non-null    object
 4   상표      438 non-null    object
 5   구       438 non-null    object
 6   Gu      438 non-null    object
dtypes: float64(1), object(6)
memory usage: 27.4+ KB

In [27]:
stations

,상호,주소,가격,셀프,상표,구,Gu
0,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),1559.0,Y,HD현대오일뱅크,강동구,강동구
1,구천면주유소,서울 강동구 구천면로 357 (암사동),1584.0,N,HD현대오일뱅크,강동구,강동구
2,(주)소모 신월주유소,서울 강동구 양재대로 1323 (성내동),1636.0,Y,GS칼텍스,강동구,강동구
3,대성석유(주)길동주유소,서울 강동구 천호대로 1168,1636.0,N,GS칼텍스,강동구,강동구
4,방아다리주유소,서울 강동구 동남로 811 (명일동),1665.0,Y,SK에너지,강동구,강동구
...,...,...,...,...,...,...,...
433,㈜새서울석유 새서울주유소,서울 강남구 압구정로 154,2158.0,N,HD현대오일뱅크,강남구,강남구
434,대청주유소,서울 강남구 개포로 654 (일원동),2195.0,N,SK에너지,강남구,강남구
435,SK논현주유소,서울 강남구 논현로 747 (논현동),2395.0,N,SK에너지,강남구,강남구
436,(주)제이제이네트웍스 제이제이주유소,서울 강남구 언주로 716,2490.0,N,HD현대오일뱅크,강남구,강남구
437,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),2598.0,N,GS칼텍스,강남구,강남구

In [28]:
del stations["Gu"]
stations

,상호,주소,가격,셀프,상표,구
0,재건에너지 재정제2주유소 고속셀프지점,서울특별시 강동구 천호대로 1246 (둔촌제2동),1559.0,Y,HD현대오일뱅크,강동구
1,구천면주유소,서울 강동구 구천면로 357 (암사동),1584.0,N,HD현대오일뱅크,강동구
2,(주)소모 신월주유소,서울 강동구 양재대로 1323 (성내동),1636.0,Y,GS칼텍스,강동구
3,대성석유(주)길동주유소,서울 강동구 천호대로 1168,1636.0,N,GS칼텍스,강동구
4,방아다리주유소,서울 강동구 동남로 811 (명일동),1665.0,Y,SK에너지,강동구
...,...,...,...,...,...,...
433,㈜새서울석유 새서울주유소,서울 강남구 압구정로 154,2158.0,N,HD현대오일뱅크,강남구
434,대청주유소,서울 강남구 개포로 654 (일원동),2195.0,N,SK에너지,강남구
435,SK논현주유소,서울 강남구 논현로 747 (논현동),2395.0,N,SK에너지,강남구
436,(주)제이제이네트웍스 제이제이주유소,서울 강남구 언주로 716,2490.0,N,HD현대오일뱅크,강남구
437,(주)만정에너지 삼보주유소,서울 강남구 봉은사로 433 (삼성동),2598.0,N,GS칼텍스,강남구

In [29]:
stations.to_csv("./result_data/02_oil_stations.csv", encoding="utf-8")